export const experienceOptions = [
  {
    label: "Less than 1 year",
    value: "0",
  },
  {
    label: "1-3 years",
    value: "1-3",
  },
  {
    label: "3-5 years",
    value: "3-5",
  },
  {
    label: "More than 5 years",
    value: ">3",
  },
];

export const educationOptions = [
  {
    label: "Doctoral degree",
    value: "doctoral",
  },
  {
    label: "Master degree",
    value: "master",
  },
  {
    label: "Bachelor degree",
    value: "bachelor",
  },
  {
    label: "Diploma / bootcamp",
    value: "diploma",
  },
];

export const countryOptions = [
  { label: "United States", value: "United States" },
  { label: "United Kingdom", value: "United Kingdom" },
  { label: "Canada", value: "Canada" },
  { label: "Australia", value: "Australia" },
  { label: "Germany", value: "Germany" },
  { label: "France", value: "France" },
  { label: "Japan", value: "Japan" },
  { label: "China", value: "China" },
  { label: "India", value: "India" },
  { label: "Brazil", value: "Brazil" },
  { label: "Russia", value: "Russia" },
  { label: "Italy", value: "Italy" },
  { label: "Spain", value: "Spain" },
  { label: "Mexico", value: "Mexico" },
  { label: "South Korea", value: "South Korea" },
  { label: "Netherlands", value: "Netherlands" },
  { label: "Sweden", value: "Sweden" },
  { label: "Switzerland", value: "Switzerland" },
  { label: "Singapore", value: "Singapore" },
  { label: "Norway", value: "Norway" },
  { label: "Denmark", value: "Denmark" },
  { label: "Finland", value: "Finland" },
  { label: "Ireland", value: "Ireland" },
  { label: "New Zealand", value: "New Zealand" },
  { label: "Belgium", value: "Belgium" },
  { label: "Austria", value: "Austria" },
  { label: "Portugal", value: "Portugal" },
  { label: "Greece", value: "Greece" },
  { label: "Poland", value: "Poland" },
  { label: "Czech Republic", value: "Czech Republic" },
  { label: "Hungary", value: "Hungary" },
  { label: "South Africa", value: "South Africa" },
  { label: "Argentina", value: "Argentina" },
  { label: "Chile", value: "Chile" },
  { label: "Colombia", value: "Colombia" },
  { label: "Malaysia", value: "Malaysia" },
  { label: "Thailand", value: "Thailand" },
  { label: "Vietnam", value: "Vietnam" },
  { label: "Philippines", value: "Philippines" },
  { label: "Indonesia", value: "Indonesia" },
  { label: "Turkey", value: "Turkey" },
  { label: "Israel", value: "Israel" },
  { label: "United Arab Emirates", value: "United Arab Emirates" },
  { label: "Saudi Arabia", value: "Saudi Arabia" },
  { label: "Egypt", value: "Egypt" },
  { label: "Morocco", value: "Morocco" },
  { label: "Kenya", value: "Kenya" },
  { label: "Nigeria", value: "Nigeria" },
  { label: "Iceland", value: "Iceland" },
  { label: "Luxembourg", value: "Luxembourg" },
];

export const skillOptions = Array.from(
  new Set([
    { label: "HTML", value: "HTML" },
    { label: "Kanban", value: "Kanban" },
    { label: "Node.js", value: "Node.js" },
    { label: "Vue.js", value: "Vue.js" },
    { label: "Redux", value: "Redux" },
    { label: "Google Cloud", value: "Google Cloud" },
    { label: "UX/UI Design", value: "UX/UI Design" },
    { label: "Jira", value: "Jira" },
    { label: "Business Development", value: "Business Development" },
    { label: "Sass", value: "Sass" },
    { label: "MongoDB", value: "MongoDB" },
    { label: "Data Analysis", value: "Data Analysis" },
    { label: "RESTful API", value: "RESTful API" },
    { label: "Java", value: "Java" },
    { label: "Bootstrap", value: "Bootstrap" },
    { label: "Firebase", value: "Firebase" },
    { label: "Ruby", value: "Ruby" },
    { label: "CSS", value: "CSS" },
    { label: "Git", value: "Git" },
    { label: "Digital Marketing", value: "Digital Marketing" },
    { label: "Heroku", value: "Heroku" },
    { label: "Express.js", value: "Express.js" },
    { label: "Spring", value: "Spring" },
    { label: "Django", value: "Django" },
    { label: "AWS", value: "AWS" },
    { label: "Azure", value: "Azure" },
    { label: "Less", value: "Less" },
    { label: "jQuery", value: "jQuery" },
    { label: "Flask", value: "Flask" },
    { label: "TypeScript", value: "TypeScript" },
    { label: "Angular", value: "Angular" },
    { label: "Ruby on Rails", value: "Ruby on Rails" },
    { label: "C++", value: "C++" },
    { label: "Swift", value: "Swift" },
    { label: "Sales", value: "Sales" },
    { label: "Product Management", value: "Product Management" },
    { label: "React", value: "React" },
    { label: "GraphQL", value: "GraphQL" },
    { label: "PHP", value: "PHP" },
    { label: "Docker", value: "Docker" },
    { label: "Kubernetes", value: "Kubernetes" },
    { label: "Python", value: "Python" },
    { label: "Laravel", value: "Laravel" },
    { label: "Agile", value: "Agile" },
    { label: "Content Strategy", value: "Content Strategy" },
  ])
);
