export const experienceOptions = [
  {
    label: "Less than 1 year",
    value: "0",
  },
  {
    label: "1-3 years",
    value: "1-3",
  },
  {
    label: "3-5 years",
    value: "3-5",
  },
  {
    label: "More than 5 years",
    value: ">3",
  },
];

export const educationOptions = [
  {
    label: "Doctoral degree",
    value: "doctoral",
  },
  {
    label: "Master degree",
    value: "master",
  },
  {
    label: "Bachelor degree",
    value: "bachelor",
  },
  {
    label: "Diploma / bootcamp",
    value: "diploma",
  },
];

export const countryOptions = [
  { label: "United States", value: "United States" },
  { label: "United Kingdom", value: "United Kingdom" },
  { label: "Canada", value: "Canada" },
  { label: "Australia", value: "Australia" },
  { label: "Germany", value: "Germany" },
  { label: "France", value: "France" },
  { label: "Japan", value: "Japan" },
  { label: "China", value: "China" },
  { label: "India", value: "India" },
  { label: "Brazil", value: "Brazil" },
  { label: "Russia", value: "Russia" },
  { label: "Italy", value: "Italy" },
  { label: "Spain", value: "Spain" },
  { label: "Mexico", value: "Mexico" },
  { label: "South Korea", value: "South Korea" },
  { label: "Netherlands", value: "Netherlands" },
  { label: "Sweden", value: "Sweden" },
  { label: "Switzerland", value: "Switzerland" },
  { label: "Singapore", value: "Singapore" },
  { label: "Norway", value: "Norway" },
  { label: "Denmark", value: "Denmark" },
  { label: "Finland", value: "Finland" },
  { label: "Ireland", value: "Ireland" },
  { label: "New Zealand", value: "New Zealand" },
  { label: "Belgium", value: "Belgium" },
  { label: "Austria", value: "Austria" },
  { label: "Portugal", value: "Portugal" },
  { label: "Greece", value: "Greece" },
  { label: "Poland", value: "Poland" },
  { label: "Czech Republic", value: "Czech Republic" },
  { label: "Hungary", value: "Hungary" },
  { label: "South Africa", value: "South Africa" },
  { label: "Argentina", value: "Argentina" },
  { label: "Chile", value: "Chile" },
  { label: "Colombia", value: "Colombia" },
  { label: "Malaysia", value: "Malaysia" },
  { label: "Thailand", value: "Thailand" },
  { label: "Vietnam", value: "Vietnam" },
  { label: "Philippines", value: "Philippines" },
  { label: "Indonesia", value: "Indonesia" },
  { label: "Turkey", value: "Turkey" },
  { label: "Israel", value: "Israel" },
  { label: "United Arab Emirates", value: "United Arab Emirates" },
  { label: "Saudi Arabia", value: "Saudi Arabia" },
  { label: "Egypt", value: "Egypt" },
  { label: "Morocco", value: "Morocco" },
  { label: "Kenya", value: "Kenya" },
  { label: "Nigeria", value: "Nigeria" },
  { label: "Iceland", value: "Iceland" },
  { label: "Luxembourg", value: "Luxembourg" },
];

export const skillOptions = Array.from(
  new Set([
    { label: "HTML", value: "HTML" },
    { label: "Kanban", value: "Kanban" },
    { label: "Node.js", value: "Node.js" },
    { label: "Vue.js", value: "Vue.js" },
    { label: "Redux", value: "Redux" },
    { label: "Google Cloud", value: "Google Cloud" },
    { label: "UX/UI Design", value: "UX/UI Design" },
    { label: "Jira", value: "Jira" },
    { label: "Business Development", value: "Business Development" },
    { label: "Sass", value: "Sass" },
    { label: "MongoDB", value: "MongoDB" },
    { label: "Data Analysis", value: "Data Analysis" },
    { label: "RESTful API", value: "RESTful API" },
    { label: "Java", value: "Java" },
    { label: "Bootstrap", value: "Bootstrap" },
    { label: "Firebase", value: "Firebase" },
    { label: "Ruby", value: "Ruby" },
    { label: "CSS", value: "CSS" },
    { label: "Git", value: "Git" },
    { label: "Digital Marketing", value: "Digital Marketing" },
    { label: "Heroku", value: "Heroku" },
    { label: "Express.js", value: "Express.js" },
    { label: "Spring", value: "Spring" },
    { label: "Django", value: "Django" },
    { label: "AWS", value: "AWS" },
    { label: "Azure", value: "Azure" },
    { label: "Less", value: "Less" },
    { label: "jQuery", value: "jQuery" },
    { label: "Flask", value: "Flask" },
    { label: "TypeScript", value: "TypeScript" },
    { label: "Angular", value: "Angular" },
    { label: "Ruby on Rails", value: "Ruby on Rails" },
    { label: "C++", value: "C++" },
    { label: "Swift", value: "Swift" },
    { label: "Sales", value: "Sales" },
    { label: "Product Management", value: "Product Management" },
    { label: "React", value: "React" },
    { label: "GraphQL", value: "GraphQL" },
    { label: "PHP", value: "PHP" },
    { label: "Docker", value: "Docker" },
    { label: "Kubernetes", value: "Kubernetes" },
    { label: "Python", value: "Python" },
    { label: "Laravel", value: "Laravel" },
    { label: "Agile", value: "Agile" },
    { label: "Content Strategy", value: "Content Strategy" },
  ])
);

export const occupationType = [
  "Full-Time",
  "Part-Time",
  "Internship",
  "Temporary",
  "Contract",
];

export const industries: string[] = [
  "Technology",
  "Finance",
  "Healthcare",
  "Education",
  "Retail",
  "Manufacturing",
  "Construction",
  "Real Estate",
  "Transportation",
  "Hospitality",
  "Marketing & Advertising",
  "Legal Services",
  "Consulting",
  "Energy & Utilities",
  "Government & Public Administration",
  "Telecommunications",
  "Entertainment & Media",
  "Non-Profit & Social Services",
  "Agriculture",
  "Automotive",
];

export const salaryRanges: string[] = [
  "50000",
  "70000",
  "100000",
  "125000",
  "150000",
];

export const skillsOptions: string[] = [
  // 🔹 Technical Skills
  "HTML",
  "CSS",
  "JavaScript",
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "TypeScript",
  "Python",
  "Java",
  "C++",
  "Swift",
  "Kotlin",
  "SQL",
  "NoSQL",
  "GraphQL",
  "REST API",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud",
  "Cybersecurity",
  "DevOps",
  "Machine Learning",
  "Data Science",
  "AI",
  "Blockchain",
  "Mobile Development",
  "Embedded Systems",
  "Software Architecture",

  // 🔹 Business & Analytics
  "Business Analysis",
  "Data Analysis",
  "Power BI",
  "Tableau",
  "Excel",
  "Google Analytics",
  "SEO",
  "Digital Marketing",
  "Product Management",
  "Project Management",
  "SCRUM",
  "Agile Methodologies",
  "CRM",
  "ERP",

  // 🔹 Finance & Accounting
  "Financial Analysis",
  "Accounting",
  "SAP",
  "QuickBooks",
  "Auditing",
  "Taxation",
  "Risk Management",
  "Investment Banking",
  "Corporate Finance",
  "Fraud Analysis",
  "Budgeting",
  "Payroll",

  // 🔹 Design & Creativity
  "UI/UX Design",
  "Figma",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Sketch",
  "Branding",
  "Typography",
  "Motion Graphics",
  "Video Editing",

  // 🔹 Sales & Marketing
  "Salesforce",
  "Google Ads",
  "Facebook Ads",
  "Content Marketing",
  "Social Media Marketing",
  "Copywriting",
  "Public Relations",
  "B2B Sales",
  "B2C Sales",
  "Lead Generation",
  "Negotiation",

  // 🔹 Soft Skills
  "Leadership",
  "Communication",
  "Problem-Solving",
  "Time Management",
  "Critical Thinking",
  "Collaboration",
  "Emotional Intelligence",
  "Customer Service",
  "Networking",
  "Conflict Resolution",
];

export const teamSizeOptions = [
  {
    label: "1-10 employees",
    value: "1-10",
  },
  {
    label: "11-50 employees",
    value: "11-50",
  },
  {
    label: "51-200 employees",
    value: "51-200",
  },
  {
    label: "201-500 employees",
    value: "201-500",
  },
  {
    label: "501-1000 employees",
    value: "501-1000",
  },
  {
    label: "1001-5000 employees",
    value: "1001-5000",
  },
  {
    label: "5001-10000 employees",
    value: "5001-10000",
  },
  {
    label: "10001+ employees",
    value: "10001+",
  },
];


export const organizationTypeOptions = [
  {
    label: "Startup",
    value: "startup",
  },
  {
    label: "Small Business",
    value: "small_business",
  },
  {
    label: "Medium Enterprise",
    value: "medium_enterprise",
  },
  {
    label: "Large Corporation",
    value: "large_corporation",
  },
  {
    label: "Non-Profit",
    value: "non_profit",
  },
  {
    label: "Government Agency",
    value: "government_agency",
  },
  {
    label: "Educational Institution",
    value: "educational_institution",
  },
  {
    label: "Freelancer",
    value: "freelancer",
  },
];
export const companyBenefitsOptions = [
  { label: "Health Insurance", value: "health_insurance" },
  { label: "Paid Time Off", value: "paid_time_off" },
  { label: "Retirement Plan", value: "retirement_plan" },
  { label: "Work From Home", value: "work_from_home" },
  { label: "Gym Membership", value: "gym_membership" },
  { label: "Stock Options", value: "stock_options" },
  { label: "Tuition Reimbursement", value: "tuition_reimbursement" },
  { label: "Childcare Assistance", value: "childcare_assistance" },
  { label: "Commuter Benefits", value: "commuter_benefits" },
  { label: "Employee Discounts", value: "employee_discounts" },
  { label: "Wellness Programs", value: "wellness_programs" },
  { label: "Professional Development", value: "professional_development" },
  { label: "Flexible Schedule", value: "flexible_schedule" },
  { label: "Parental Leave", value: "parental_leave" },
  { label: "Life Insurance", value: "life_insurance" },
];
